# Dependencies
markdown:         redcarpet
pygments:         true

# Setup
title:            Nikhil Daga
tagline:          '- Entrepreneur, Web Developer, Astrologer and Equity Analyst'
description:      'Nikhil Daga -  Entrepreneur, Web Developer, Astrologer and Equity Analyst'
url:              http://nikhilda.ga
baseurl:          /blog

author:
  name:           'Nikhil Daga'
  url:            https://google.com/+nikhildaga

paginate:         5

# Custom vars
version:          1.0.0
